### ISSUE TITLE
Server not Starting

### ISSUE THREAD

**Issue by umarhyatt00** [nccgroup/house#51]
When I run command:
python3 app.py 8000
I get the following error:
Traceback (most recent call last):
  File "/Users/uh/Downloads/house/app.py", line 23, in <module>
    from houseGlobal import house_global, app, socketio, random_token
  File "/Users/uh/Downloads/house/houseGlobal.py", line 23, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

OS:
Same on MAC and Kali.
Thank you for help.

**Comment by umarhyatt00** [comment]
There were some missing dependencies which i have manually installed and it fixed the issue.
